-- Cinematic: MySkillCinematic
-- 2 keyframes, 0.50s duration
-- Generated by Cinematic Sequencer

local module = {}

module.Keyframes = {
	{time=0.00, cframe=CFrame.new(-193.8888,92.2709,229.5611,0.9489,0.1445,-0.2805,-0.0000,0.8889,0.4581,0.3155,-0.4347,0.8435), fov=70, easing="Sine", easingDir="InOut"},
	{time=0.50, cframe=CFrame.new(-171.7153,114.9389,193.8370,-0.6102,-0.4917,0.6212,-0.0000,0.7841,0.6206,-0.7922,0.3787,-0.4785), fov=70, easing="Sine", easingDir="InOut"},
}

-- Play function (client-side, paste into LocalScript)
function module.Play()
	local cam = workspace.CurrentCamera
	local TS = game:GetService('TweenService')
	local RS = game:GetService('RunService')
	local kfs = module.Keyframes
	local saved = cam.CameraType
	cam.CameraType = Enum.CameraType.Scriptable
	cam.CFrame = kfs[1].cframe
	cam.FieldOfView = kfs[1].fov
	local t0 = tick()
	local fired = {}
	local conn
	conn = RS.RenderStepped:Connect(function()
		local e = tick() - t0
		if e > kfs[#kfs].time + 0.3 then
			cam.CameraType = saved; conn:Disconnect(); return
		end
		local pK,nK = kfs[1],kfs[#kfs]
		for i=1,#kfs-1 do
			if e>=kfs[i].time and e<kfs[i+1].time then
				pK=kfs[i]; nK=kfs[i+1]; break
			end
		end
		local sd = nK.time - pK.time
		local st = sd>0 and math.clamp((e-pK.time)/sd,0,1) or 1
		local es = Enum.EasingStyle[nK.easing] or Enum.EasingStyle.Sine
		local ed = Enum.EasingDirection[nK.easingDir] or Enum.EasingDirection.InOut
		local v = TS:GetValue(st,es,ed)
		cam.CFrame = pK.cframe:Lerp(nK.cframe,v)
		cam.FieldOfView = pK.fov+(nK.fov-pK.fov)*v
	end)
end

return module