-- Skill: MySkill
-- Generated by Skill Editor Plugin

local module = {}

module.Animations = {
	{time=3.56, duration=1.00, animId="rbxassetid://0", speed=1.0, castPoint=0.30, cancelPoint=0.70, canInterrupt=true, name="Anim"},
}

return module